name: glob-changed-files-action
description: Action to expand glob patterns by changed files of pull request
inputs:
  paths:
    description: Glob patterns (multiline)
    required: true
  paths-fallback:
    description: Glob patterns to fallback to wildcard (multiline)
    required: false
  outputs:
    description: Paths to set into outputs in form of NAME=PATH (multiline)
    required: true
  outputs-encoding:
    description: Encoding of outputs, either multiline or json
    required: true
    default: multiline
  token:
    description: GitHub token to list the changed files
    required: true
    default: ${{ github.token }}
runs:
  using: 'node20'
  main: 'dist/index.js'
