name: reduce
description: reduce paths by changed files in a pull request
inputs:
  paths:
    description: paths to match (multiline)
    required: true
  paths-always:
    description: paths to fallback to wildcard (multiline)
    required: true
  transform:
    description: paths to transform (multiline)
    required: true
  token:
    description: GitHub token to list files
    required: true
    default: ${{ github.token }}
runs:
  using: 'node12'
  main: 'dist/index.js'
